
FROM ubuntu:20.04

SHELL ["/bin/bash", "-c"]

# 時刻設定
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# キーボード設定
ENV DEBIAN_FRONTEND=noninteractive

# 環境設定
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

# aptアップグレード&設定
RUN apt update -y 
RUN apt upgrade -y 

RUN apt-get update -y 
RUN apt-get upgrade -y 

RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# エディタ
RUN apt-get install -y nano

# python
RUN apt-get install -y python3.9
RUN apt-get install -y python3-pip

# python-lib
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install discord.py[voice]==1.7.3

WORKDIR /root

COPY namingway.py /root/namingway.py

ENTRYPOINT python3 namingway.py _TOKEN_
